# dryRun: true

logging:
  # Enables low level command output
  showCommands: true

# Disable tearing down the testing environment
#noTearDown: true

kafka:
  bootstrapServer: my-cluster-kafka-bootstrap.kafka:9092
  namespace: kafka

strimzi:
  cluster: my-cluster
