# dryRun: true

logging:
  # Enable/Disable low level command output
  showCommands: true

  # Enable/Disable Event recorder  output
  showEvents: false

# Enable/Disable tearing down the testing environment
noTearDown: false

kafka:
  bootstrapServer: my-cluster-kafka-bootstrap.kafka:9092
  namespace: kafka

strimzi:
  cluster: my-cluster
